const USER_TYPE = {
  USER: "USER",
  MENTOR: "MENTOR",
  ADMIN: "ADMIN",
};
const ROLE = ["USER", "MENTOR", "ADMIN"];
const DATA_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

module.exports = {
  DATA_STATUS: DATA_STATUS,
  USER_TYPE: USER_TYPE,
  ROLE: ROLE,
};
